Makefile.am
build-aux/version.sh

The current Makefile assume an in tree build. Some build systems are
compiling out of tree. Fix the relative paths to allow out of tree
builds.
Signed-off-by: Alexandre Belloni <alexandre.belloni@free-electrons.com>

Allow building out of tree

---

src/libmaxtouch/i2c_dev/i2c_dev_device.c
src/libmaxtouch/libmaxtouch.c
src/mxt-app/diagnostic_data.c
src/mxt-app/mxt_app.h

The diagnostic data algorithm was only parsing one type of diagnostic data, the order of the columns was generated wrong.
Update algorithm with reference to documentation. Tested on Pixel 2 chromebook, but needs independent verification.

Fix issues with self cap diagnostic data

---

src/libmaxtouch/sysfs/sysfs_device.c

When read hits EOF of the mem_access file (for example if the kernel driver
has sized the file incorrectly) it otherwise gets caught in an infinite
loop because of the zero length read.
Signed-off-by: Nick Dyer <nick.dyer@itdev.co.uk>

Handle zero reads correctly

---

autogen.sh

aclocal 1.11 triggers a fatal error if this m4 directory doesn't exist.

Create m4 directory if it doesn't exist

---

configure.ac

When using --disable-man, manual page were enabled. Ensure they just
stay disabled.

Make --disable-man work as expected

---

src/libmaxtouch/utilfuncs.c
src/libmaxtouch/utilfuncs.h
src/mxt-app/mxt_app.c

Update write command to allow spaces in between bytes.
In addition to this, other options can appear between and after bytes
without interfering with the parsing.
fixes #37

Allow space separated entries for register bytes

---

src/libmaxtouch/utilfuncs.c
src/test/test_utilfuncs.c

to_digit now returns an mxt_rc enum value to provide feedback for
parsing, while the decimal value is passed in as an argument.
Unit tests updated to check for erroneous string input.

Fix return value from to_digit

---

README.md
src/mxt-app/diagnostic_data.c
src/mxt-app/mxt_app.c
src/mxt-app/mxt_app.h

Updated from https://github.com/atmel-maxtouch/mxt-app/pull/38, removing static function mxt_debug_insert_data_ast, which was preventing compilation.

Introduce new command "--active-stylus-delta" to capture the deltas of Active Stylus

---

README.md
src/libmaxtouch/i2c_dev/i2c_dev_device.c
src/libmaxtouch/i2c_dev/i2c_dev_device.h
src/libmaxtouch/libmaxtouch.c
src/libmaxtouch/libmaxtouch.h
src/mxt-app/mxt_app.c

Adds the --block-size option to mxt-app, which provides the I2C block
size information.
Also adds the block size value to the i2c_dev_device, rather than using
the defined value in all instances.
See https://github.com/atmel-maxtouch/mxt-app/issues/45  for original requirements.

Add --block-size option to mxt-app

---

src/libmaxtouch/sysfs/dmesg.c

On some systems, the kernel dmesg ring buffer is enormous, and we have
seen issues in allocating this amount of memory.
Signed-off-by: Nick Dyer <nick.dyer@itdev.co.uk>

Limit maximum dmesg buffer size

---

src/libmaxtouch/sysfs/sysfs_device.c

ret is boolean so the comparison (ret < 0) will always evaluate to false.
Change it to the proper type, int
Signed-off-by: Alexandre Belloni <alexandre.belloni@free-electrons.com>

Fix ret type in read_boolean_file

---

src/mxt-app/diagnostic_data.c

TKT-016076: BUG_FIXED - This is a bug fix of my commit a46f80ec20f69a9f801b6ad0395377e46bdc1535. Because in that commit, the variable ctx->active_stylus may be used without been initialized, and hence can generate random behavior. For example, with command "./mxt-app --frames 2 --references --debug-dump ref.csv", but the output ref.csv may be with active stylus headers incorrectly generated, it shall be mutual cap reference headers.

Problem Report: Uninitialized variable being used and may cause incorrect content been debug dumped.

---

autogen.sh

Buildroot does not execute the autogen.sh so we cannot build it with it. With the .empty file in the m4 folder the folder is always created.

Add .empty in m4 folder and remove mkdir in autogen

---

src/test/run_unit_tests.c

Typoed + instead of # in run_unit_tests.c.

Fix #include typo

---

configure.ac
src/mxt-app/bridge.c

Fixes build problems around use of asprintf.

Explicit _GNU_SOURCE in bridge.c

---

src/mxt-app/bootloader.c

After flashing and returning to app mode, the connection is released
(mxt_unref_conn() + mxt_free_device()) and recreated. During
initializing new 'struct mxt_conn_info', the 'i2c_adapter' value from
'struct flash_context' is used to set i2c bus:
new_conn->i2c_dev.adapter = fw.i2c_adapter;
The i2c_adapter variable is always 0, when device was specified by i2c
bus and address from the parameters.
Signed-off-by: Ondrej Pik <ondrej@amarulasolutions.com>

Ensure i2c_adapter var is set properly in bootloader

---

src/libmaxtouch/libmaxtouch.c

Added delay after device reset.
Allows device to complete reset before additional I2C access.

Add delay after device reset

---

src/mxt-app/mxt_app.h

Its defined in src/mxt-app/signal.c like
volatile sig_atomic_t mxt_sigint_rx = 0;
Therefore we do not need another definition in header file, this fixes
the build with -fno-common ( which is default with gcc 10+)
Signed-off-by: Khem Raj <raj.khem@gmail.com>

Make mxt_sigint_rx extern in header file

---

src/mxt-app/diagnostic_data.c

Remove code to disable T100 in broken-line and sensor-variant test.  Causing T6 return message to set CFGERR bit in status byte instead of CAL bit.

Removed code to disable T100 in broken-line and sensor-varant test

---

src/mxt-app/bridge.c

MAX limit for string in line buffer increased from 10000 to 12000 to accommodate devices with larger configurations.

increase max buffer line size

---

src/libmaxtouch/sysfs/sysfs_device.c

This pull request helps you to remove the compiler warning of trailing redundant ';'.

Eliminated compiler warning by removing redundant trailing `;`.

---

src/libmaxtouch/libmaxtouch.h
src/libmaxtouch/usb/usb_device.c
src/libmaxtouch/usb/usb_device.h
src/mxt-app/bootloader.c

-- Fix flashing using bridge board
-- Bridge board tries to auto find I2C address resulting in exiting bootloader mode too early
-- Assign bootloader address based on app slave_address
-- maXTouch device is not assigned same device # on reset
-- Removed usb_device variable check after reset

Fix for bridge board flashing

---

src/libmaxtouch/debugfs/debugfs_device.c
src/libmaxtouch/info_block.c
src/libmaxtouch/libmaxtouch.c
src/libmaxtouch/sysfs/sysfs_device.c
src/libmaxtouch/sysfs/sysfs_device.h

Integrate reset fix when using I2c-dev interface and debugfs attribute files to reset the chip
Updated branch to latest on master before committing new changes to i2c_dev_fix branch

I2cdev reset fix

---

src/libmaxtouch/debugfs/debugfs_device.c

Fixed possible case where debug_fs_set_irq() function can reach end of function with no return value

Fix end of control issue

---

src/mxt-app/diagnostic_data.c

Modification allows non zero origin debug dumps through T37.
Pass used for 2nd touchscreen or slider to acquire origin start point and size
Code can be used in both zero origin and non zero origin

Allow non zero origin debug dumps
